'use client';

import React from 'react';
import type { Dispatch, SetStateAction } from 'react';
import type { NewEventState } from '@/app/types/events';

type Props = {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: () => Promise<void> | void;
  newEvent: NewEventState;
  setNewEvent: Dispatch<SetStateAction<NewEventState>>;
};

function parseCsv(v: string): string[] {
  return v
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean);
}

export default function AddEventModal({ isOpen, onClose, onSubmit, newEvent, setNewEvent }: Props) {
  if (!isOpen) return null;

  // ✅ FIX: Add optional chaining
  const streetsText = (newEvent.streets || []).join(', ');

  const canSubmit =
    !!newEvent.title.trim() &&
    (newEvent.streets?.length ?? 0) > 0;

  return (
    <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
      <div className="bg-theme-surface rounded-2xl shadow-xl max-w-2xl w-full max-h-[90vh] overflow-y-auto border border-[var(--color-border)]">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-[var(--color-border)]">
          <h2 className="text-xl sm:text-2xl font-semibold text-theme-text">Add New Event</h2>
          <button
            onClick={onClose}
            className="inline-flex h-9 w-9 items-center justify-center rounded-xl
                       border border-[var(--color-border)] bg-theme-surface text-theme-muted
                       hover:bg-[rgba(var(--color-primary-500-rgb),0.06)] transition-colors text-xl font-bold"
            aria-label="Close"
          >
            ×
          </button>
        </div>

        {/* Body */}
        <div className="p-6 space-y-6">
          {/* Event ID (Optional - Auto-generated by backend) */}
          <div>
            <label className="block text-sm font-medium text-theme-text mb-2">
              Event ID <span className="text-theme-muted text-xs">(Optional - Auto-generated)</span>
            </label>
            <input
              value={newEvent.id || ''}
              onChange={(e) => setNewEvent((p) => ({ ...p, id: e.target.value }))}
              className="w-full rounded-xl border border-[var(--color-border)] bg-theme-surface px-4 py-2 text-theme-text
                         focus:outline-none focus:ring-2 focus:ring-[rgba(var(--color-primary-500-rgb),0.30)]"
              placeholder="Leave empty for auto-generation (e.g. evt_1735446000)"
            />
            <p className="mt-1 text-xs text-theme-muted">
              If left blank, backend will generate ID automatically
            </p>
          </div>

          {/* Title (Required) */}
          <div>
            <label className="block text-sm font-medium text-theme-text mb-2">
              Event Title *
            </label>
            <input
              value={newEvent.title || ''}
              onChange={(e) => setNewEvent((p) => ({ ...p, title: e.target.value }))}
              className="w-full rounded-xl border border-[var(--color-border)] bg-theme-surface px-4 py-2 text-theme-text
                         focus:outline-none focus:ring-2 focus:ring-[rgba(var(--color-primary-500-rgb),0.30)]"
              placeholder="e.g. Road Maintenance - MG Road"
            />
          </div>

          {/* Streets (Required) */}
          <div>
            <label className="block text-sm font-medium text-theme-text mb-2">
              Affected Streets (comma-separated) *
            </label>
            <input
              value={streetsText}
              onChange={(e) => setNewEvent((p) => ({ ...p, streets: parseCsv(e.target.value) }))}
              className="w-full rounded-xl border border-[var(--color-border)] bg-theme-surface px-4 py-2 text-theme-text
                         focus:outline-none focus:ring-2 focus:ring-[rgba(var(--color-primary-500-rgb),0.30)]"
              placeholder="e.g. :119822693#1_0, :119822693#1_1, gneE6_0"
            />
            <p className="mt-1 text-xs text-theme-muted">
              Enter SUMO edge IDs separated by commas. These streets will be blocked during the event.
            </p>
            {/* ✅ FIX: Use optional chaining */}
            {(newEvent.streets?.length ?? 0) > 0 && (
              <div className="mt-2 flex flex-wrap gap-2">
                {newEvent.streets.map((street, idx) => (
                  <span
                    key={idx}
                    className="inline-flex items-center gap-1 px-3 py-1 rounded-lg
                               bg-[rgba(var(--color-primary-500-rgb),0.1)]
                               border border-[rgba(var(--color-primary-500-rgb),0.2)]
                               text-sm text-theme-text"
                  >
                    {street}
                    <button
                      type="button"
                      onClick={() =>
                        setNewEvent((p) => ({
                          ...p,
                          streets: (p.streets || []).filter((s) => s !== street),
                        }))
                      }
                      className="ml-1 text-theme-muted hover:text-red-500 transition-colors"
                    >
                      ×
                    </button>
                  </span>
                ))}
              </div>
            )}
          </div>

          {/* Info Box */}
          <div className="rounded-2xl border border-[var(--color-border)] bg-[rgba(var(--color-primary-500-rgb),0.05)] p-4">
            <div className="flex items-start gap-3">
              <div className="flex-shrink-0 mt-0.5">
                <svg
                  className="w-5 h-5 text-[var(--color-primary)]"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                  />
                </svg>
              </div>
              <div className="flex-1">
                <h4 className="text-sm font-semibold text-theme-text mb-1">
                  How to select streets
                </h4>
                <p className="text-sm text-theme-muted mb-2">
                  Go to the <strong>Simulation page</strong> to view and select streets on the live map.
                  Click on streets to get their edge IDs, then paste them here.
                </p>
                <button
                  type="button"
                  onClick={() => window.open('/dashboard/simulation', '_blank')}
                  className="inline-flex items-center gap-2 px-4 py-2 bg-[var(--color-primary)]
                             hover:bg-[var(--color-primary-500)] text-white rounded-lg
                             transition-colors shadow-sm font-medium text-sm"
                >
                  <svg
                    className="w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                    />
                  </svg>
                  Open Simulation (New Tab)
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 p-6 border-t border-[var(--color-border)]">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-xl text-theme-text border border-[var(--color-border)] bg-theme-surface
                       hover:bg-[rgba(var(--color-primary-500-rgb),0.06)] transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={onSubmit}
            disabled={!canSubmit}
            className="px-6 py-2 bg-[var(--color-primary)] hover:bg-[var(--color-primary-500)]
                       text-white rounded-xl transition-colors disabled:opacity-50 disabled:cursor-not-allowed
                       shadow-sm"
            title={!canSubmit ? 'Fill all required fields (title and streets)' : undefined}
          >
            Create Event
          </button>
        </div>
      </div>
    </div>
  );
}

/**
 * Helper to convert form state to API payload
 */
export function toEventPayload(form: { id: string; title: string; streets: string[] }) {
  const payload: any = {
    title: form.title.trim(),
    streets: form.streets || [], // ✅ FIX: Ensure array
  };

  // Only include ID if user provided one (otherwise backend auto-generates)
  if (form.id?.trim()) {
    payload.id = form.id.trim();
  }

  return payload;
}
