"""
Simple Traffic Light Logic Generator (CORRECTED)
Generates only RL-controlled programs for specified junctions.
All other junctions use their default SUMO programs.
"""

# actuator based
import os
import sys
import yaml
import traci
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom.minidom import parseString
from sumo_simulator import SumoSimulator


def generate_rl_tls_programs(config_path="config.yaml"):
    """
    Generates RL-controlled programs ONLY for controlled junctions.
    Other junctions keep their default SUMO behavior.
    """
    print("=" * 70)
    print("GENERATING RL TRAFFIC LIGHT PROGRAMS")
    print("=" * 70)

    with open(config_path, "r") as f:
        config = yaml.safe_load(f)

    print("\nStarting temporary SUMO simulation...")

    # Initialize Simulator using the new signature we created
    # We pass 'config' so it picks up step_length and other settings
    temp_sim = SumoSimulator(config["sumo"]["config_file"], config, gui=False)

    controlled_junction_ids = config["system"]["controlled_junctions"]
    print(f"Target Junctions from Config: {len(controlled_junction_ids)}")

    # Generate XML Root
    xml_root = Element("additional")

    count = 0
    for tls_id in controlled_junction_ids:
        # Check if junction exists in the network
        if tls_id not in temp_sim.junctions:
            print(
                f"  ⚠ Warning: Junction '{tls_id}' in config but not found in SUMO network. Skipping."
            )
            continue

        # Get controlled links to map roads to signals
        try:
            controlled_links = traci.trafficlight.getControlledLinks(tls_id)
        except traci.TraCIException:
            print(f"  ⚠ Error: Could not get links for '{tls_id}'. Skipping.")
            continue

        junction_info = temp_sim.junctions[tls_id]
        incoming_roads = junction_info["incoming_roads"]
        num_signals = len(controlled_links)

        # Create tlLogic Element
        # programID='rl_program' is what we will switch to during training
        tl_logic = SubElement(
            xml_root,
            "tlLogic",
            {"id": tls_id, "type": "static", "programID": "rl_program", "offset": "0"},
        )

        # Create one Green Phase per Incoming Road
        # This ensures one road moves at a time (Safe/Robust approach)
        for phase_idx, road in enumerate(incoming_roads):
            # 1. Start with All Red
            state = ["r"] * num_signals

            # 2. Find which signals belong to the current 'road' and make them Green
            for link_idx, links in enumerate(controlled_links):
                # Links is a list of connections for this signal index
                if links:
                    # links[0][0] is the incoming lane ID (e.g., "edge_0_1")
                    from_lane = links[0][0]
                    from_edge = traci.lane.getEdgeID(from_lane)

                    if from_edge == road:
                        state[link_idx] = "G"

            state_str = "".join(state)

            # 3. Add Green Phase
            SubElement(
                tl_logic,
                "phase",
                {"duration": str(config["fdrl"]["green_time"]), "state": state_str},
            )

            # 4. Add Yellow Phase
            # FIX: Replace both Priority Green ('G') and Yield Green ('g') with Yellow ('y')
            yellow_state = state_str.replace("G", "y").replace("g", "y")

            SubElement(
                tl_logic,
                "phase",
                {"duration": str(config["fdrl"]["yellow_time"]), "state": yellow_state},
            )

        count += 1
        print(f"  ✓ {tls_id}: Generated {len(incoming_roads)} phases (plus yellow)")

    temp_sim.close()

    # Format and Save XML
    xml_string = tostring(xml_root, "utf-8")
    pretty_xml = parseString(xml_string).toprettyxml(indent="  ")
    # Remove empty lines generated by pretty print
    pretty_xml = "\n".join([line for line in pretty_xml.split("\n") if line.strip()])

    # Determine output path relative to the .sumocfg file
    sumo_dir = os.path.dirname(config["sumo"]["config_file"])
    output_path = os.path.join(sumo_dir, "rl_traffic_lights.add.xml")

    with open(output_path, "w") as f:
        f.write(pretty_xml)

    print(f"\n{'=' * 70}")
    print(f"SUCCESS: RL programs generated for {count} junctions")
    print(f"  Output File: {output_path}")
    print(f"{'=' * 70}")
    print("\nIMPORTANT NEXT STEP:")
    print(f"1. Open {config['sumo']['config_file']}")
    print("2. Ensure this line exists inside the <input> block:")
    print(f'   <additional-files value="rl_traffic_lights.add.xml"/>')
    print("=" * 70)


if __name__ == "__main__":
    generate_rl_tls_programs()
